#set($package-dir = $package.replace(".", "/"))
#set($dst-ver-dir = $group.replace("-", "_"))
package:
  generate:
    - directory-map:
        source: pkg-dir
        destination: ${package-dir}
    - directory-map:
        source: ver-dir
        destination: ${dst-ver-dir}
